/*
 * This file was automatically generated by EvoSuite
 * Thu Oct 18 12:36:43 GMT 2018
 */

package tutorial;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import tutorial.Node;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Node_ESTest extends Node_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Integer integer0 = new Integer(2086);
      Node<Object> node0 = new Node<Object>(integer0);
      Node<Object> node1 = new Node<Object>(node0);
      node1.setNext(node0);
      assertFalse(node0.equals((Object)node1));
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Node<String> node0 = new Node<String>("LzdM>;:#IJSzfHNY&V/");
      String string0 = node0.getObject();
      assertEquals("LzdM>;:#IJSzfHNY&V/", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Integer integer0 = new Integer(2086);
      Node<Object> node0 = new Node<Object>(integer0);
      node0.setNext(node0);
      Node<Object> node1 = node0.getNext();
      assertSame(node0, node1);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Node<String> node0 = new Node<String>((String) null);
      String string0 = node0.getObject();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Integer integer0 = new Integer(2086);
      Node<Object> node0 = new Node<Object>(integer0);
      Node<Object> node1 = node0.getNext();
      assertNull(node1);
  }
}
